services:
  test:
    build:
      context: .
      args:
        UV_NO_DEV: 0
    environment:
      SCHEDULER_CRONTAB_EXPR: ${SCHEDULER_CRONTAB_EXPR}
      SCHEDULER_MISFIRE_GRACE_TIME: ${SCHEDULER_MISFIRE_GRACE_TIME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      UV_NO_DEV: 0
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/.venv
    restart: "no"
    command: ["tail", "-f", "/dev/null"]
  db:
    image: postgres:18.1
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: "no"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
